version: '3.7'

networks:
  default:
    driver: bridge

services:
    flask:
        build:
            context: .
            dockerfile: flask
        ports: 
            - "5000:5000"
        expose: 
            - "5000"

        environment: 
            - FLASK_APP=/usr/src/app/app.py
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
        networks: 
            - default

# production
    react:
        build: 
            context: .
            dockerfile: react
        expose:
            - "3001"
        ports:
            - "3001:3001" # production
        links:
            - "flask:flask"
        networks: 
            - default

    react2:
        build: 
            context: .
            dockerfile: react2
        expose:
            - "3000"
        ports:
            - "3000:3000"
        links:
            - "flask:flask"
        networks: 
            - default

    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_DATABASE=testdb
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes: 
            - ./dbstuff/mongo:/data/db
        ports: 
            - "27017-27019:27017-27019"